### ISSUE TITLE
Using Raw KeyCode Input

### ISSUE THREAD

**Issue by lucashaley** [vcolleen/Ngeru#8]
@vcolleen I need a really good reason why you are polling for raw keycodes in your character controller.

See line 37 in the current Master branch:

`if(Input.GetKey (KeyCode.D))`

It is a far better idea to poll the Input system, using code like `Input.GetAxis`. Please convince me why you're not!

**Comment by vcolleen** [comment]
Sorry, I'll be using that now. I was just following tutorials before telling me to use that line of code and it didn't occur to me to use the Input system. My mistake, thanks for pointing it out.
